### ISSUE TITLE
Refactor PocketALBApplication

### ISSUE THREAD

**Issue by kkyeboah** [Pocket/terraform-modules#95]
**Describe the issue**
The PocketALBApplication module/class has become bloated and needs to be refactored.

**Comment by bassrock** [comment]
https://github.com/Pocket/parser-graphql-wrapper/pull/29/files/c1467e69c38e35dcc0f535efe1bf37e65292ba54#r580416704

As part of the refactor it should be able to add Security Groups to the application.
